version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
install:
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.App.Prometheus.Pushgateway.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: UjMEFzKXdmJqBeN+MHnLa0jhJITWtXfXf82OM9iSoTh5pjGKnVDnmXgoPlER4IWY
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: SZ0dhuJHdvFvWct/ReyYVIO0JuoQhlvFNLpQW6ovIGh8jTildsQdZHRpJxfzIRsq
  artifact: /Seq.App.Prometheus.Pushgateway.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
