version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
install:
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.App.Prometheus.Pushgateway.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: TODO
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: TODO
  artifact: /Seq.App.Prometheus.Pushgateway.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
